### ISSUE TITLE
Uploading a photo to Wikipedia

### ISSUE THREAD

**Issue by junaruga** [penk/MainboardTerminal#1]
Hello,

Thank you for your great project. I am editing [Framework's Wikipedia page](https://en.wikipedia.org/wiki/Framework_Computer). And I would like to see [this photo, images/mainboard-terminal-heroshot.jpg](https://github.com/penk/MainboardTerminal/blob/master/images/mainboard-terminal-heroshot.jpg) on the Wikipedia page.

Do you mind that you upload the photo image by yourself there or you declare at least the image with "CC BY-SA 4.0" license? I tried to upload the image to the Wikipedia. But it seems the MIT licence is not allowed to upload it. So, this repository's possible license might be "MIT or CC BY-SA 4.0".

If you declare the license, I can upload it. However it seems it's less trouble when you, the actual license holder would upload it, seeing other cases.

Here is the [example](https://github.com/FrameworkComputer/Mainboard/blob/main/LICENSE) of "CC BY-SA 4.0" license file.

How to upload the image to the Wikipedia: Create your account on Wikipedia, and upload at [UploadWizard](https://commons.wikimedia.org/wiki/Special:UploadWizard). The [document](https://en.wikipedia.org/wiki/Wikipedia:Uploading_images).

Thank you!

**Comment by penk** [comment]
@junaruga thanks for the report, let re re-license it.

**Comment by junaruga** [comment]
Thank you! As a reference, here is an example of license "MIT or CC-BY-SA", https://github.com/assaf/uuid#license- . But I might recommend "CC BY-SA 4.0" rather than "CC-BY-SA". as the "CC BY-SA 4.0" is Wikipedia's default license.

**Comment by penk** [comment]
Fixed in https://github.com/penk/MainboardTerminal/commit/ec24c0ecd101385beadf120c304ea125c5675419

**Comment by junaruga** [comment]
Thank you!

**Comment by junaruga** [comment]
Your photo was uploaded to the [Framework's Wikipeida page](https://en.wikipedia.org/wiki/Framework_Computer) now! Thank you.
